# Generated by Django 4.2.3 on 2023-09-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bmr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_calories',
            field=models.IntegerField(default=0),
        ),
    ]
