# Generated by Django 4.2.3 on 2023-09-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
