# Generated by Django 4.2.3 on 2023-09-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='starting_weight',
            field=models.FloatField(default=0),
        ),
    ]
