# Generated by Django 4.2.3 on 2023-09-04 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0002_alter_foodlog_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightlog',
            name='date',
        ),
        migrations.AddField(
            model_name='weightlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 23, 18, 3, 795253, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 23, 18, 3, 795253, tzinfo=datetime.timezone.utc)),
        ),
    ]
