# Generated by Django 4.2.3 on 2023-09-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0002_alter_user_bmr_alter_user_daily_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='objetive',
            new_name='objective',
        ),
    ]
