# Generated by Django 4.2.3 on 2023-09-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0002_alter_user_age_alter_user_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_weight',
            field=models.FloatField(default=0),
        ),
    ]
