# Generated by Django 4.2.3 on 2023-09-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0003_rename_objetive_user_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
