# Generated by Django 4.2.3 on 2023-09-05 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0003_remove_weightlog_date_weightlog_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 17, 3, 12, 671314)),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 17, 3, 12, 670314)),
        ),
    ]
