# Generated by Django 4.2.3 on 2023-09-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0004_foodlog_weight_alter_foodlog_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
