# Generated by Django 4.2.3 on 2023-09-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0004_alter_foodlog_calories_alter_foodlog_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
