# Generated by Django 4.2.3 on 2023-09-06 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0007_alter_foodlog_timestamp_alter_weightlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 23, 2, 0, 860130)),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 23, 2, 0, 859098)),
        ),
    ]
