# Generated by Django 4.2.3 on 2023-09-14 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithub', '0008_alter_foodlog_timestamp_alter_weightlog_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlog',
            old_name='weight',
            new_name='serving',
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 16, 39, 55, 394153)),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 16, 39, 55, 394153)),
        ),
    ]
